-- DROP USER "lucas.lara";

CREATE USER "lucas.lara"
-- IDENTIFIED BY <password>
;

CREATE TABLE "lucas.lara"."DIM_ARBITRO" 
   (	"ID_ARBITRO" NUMBER(*,0) NOT NULL ENABLE, 
	"ARBITRO" VARCHAR2(100) NOT NULL ENABLE, 
	"NACIONALIDAD" VARCHAR2(100) NOT NULL ENABLE, 
	"NOMBRE" VARCHAR2(100) NOT NULL ENABLE, 
	 CONSTRAINT "DIM_ARBITRO_PK" PRIMARY KEY ("ID_ARBITRO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

CREATE UNIQUE INDEX "lucas.lara"."DIM_ARBITRO_PK" ON "lucas.lara"."DIM_ARBITRO" ("ID_ARBITRO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
;

CREATE TABLE "lucas.lara"."DIM_COMPETICION" 
   (	"ID_COMPETICION" NUMBER(*,0) NOT NULL ENABLE, 
	"COMPETICION" VARCHAR2(100) NOT NULL ENABLE, 
	"PAIS" VARCHAR2(100) NOT NULL ENABLE, 
	"NOMBRE" VARCHAR2(100) NOT NULL ENABLE, 
	 CONSTRAINT "DIM_COMPETICION_PK" PRIMARY KEY ("ID_COMPETICION")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

CREATE UNIQUE INDEX "lucas.lara"."DIM_COMPETICION_PK" ON "lucas.lara"."DIM_COMPETICION" ("ID_COMPETICION") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
;

CREATE TABLE "lucas.lara"."DIM_EQUIPO" 
   (	"ID_EQUIPO" NUMBER(*,0) NOT NULL ENABLE, 
	"EQUIPO" VARCHAR2(100) NOT NULL ENABLE, 
	"NOMBRE" VARCHAR2(100) NOT NULL ENABLE, 
	"PAIS" VARCHAR2(100) NOT NULL ENABLE, 
	"ENTRENADOR" VARCHAR2(100) NOT NULL ENABLE, 
	 CONSTRAINT "DIM_EQUIPO_PK" PRIMARY KEY ("ID_EQUIPO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

CREATE UNIQUE INDEX "lucas.lara"."DIM_EQUIPO_PK" ON "lucas.lara"."DIM_EQUIPO" ("ID_EQUIPO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
;

CREATE TABLE "lucas.lara"."DIM_ESTADIO" 
   (	"ID_ESTADIO" NUMBER(*,0) NOT NULL ENABLE, 
	"ESTADIO" VARCHAR2(100) NOT NULL ENABLE, 
	"UBICACION" VARCHAR2(200) NOT NULL ENABLE, 
	"NOMBRE" VARCHAR2(100) NOT NULL ENABLE, 
	 CONSTRAINT "DIM_ESTADIO_PK" PRIMARY KEY ("ID_ESTADIO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

CREATE UNIQUE INDEX "lucas.lara"."DIM_ESTADIO_PK" ON "lucas.lara"."DIM_ESTADIO" ("ID_ESTADIO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
;

CREATE TABLE "lucas.lara"."DIM_FECHA" 
   (	"ID_FECHA" NUMBER(*,0) NOT NULL ENABLE, 
	"FECHA" VARCHAR2(100) NOT NULL ENABLE, 
	"DIA" VARCHAR2(100) NOT NULL ENABLE, 
	"MES" VARCHAR2(100) NOT NULL ENABLE, 
	"TEMPORADA" VARCHAR2(100) NOT NULL ENABLE, 
	"AÑO" NUMBER(*,0) NOT NULL ENABLE, 
	 CONSTRAINT "DIM_FECHA_PK" PRIMARY KEY ("ID_FECHA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

CREATE UNIQUE INDEX "lucas.lara"."DIM_FECHA_PK" ON "lucas.lara"."DIM_FECHA" ("ID_FECHA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
;

CREATE TABLE "lucas.lara"."DIM_LESION" 
   (	"ID_LESION" NUMBER(*,0) NOT NULL ENABLE, 
	"LESION" VARCHAR2(150) NOT NULL ENABLE, 
	"JUGADOR" VARCHAR2(100) NOT NULL ENABLE, 
	"TIEMPO_RECUPERACION" VARCHAR2(100) NOT NULL ENABLE, 
	 CONSTRAINT "DIM_LESION_PK" PRIMARY KEY ("ID_LESION")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

CREATE UNIQUE INDEX "lucas.lara"."DIM_LESION_PK" ON "lucas.lara"."DIM_LESION" ("ID_LESION") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
;

CREATE TABLE "lucas.lara"."FACT_PARTIDO" 
   (	"ID_FECHA" NUMBER(*,0) NOT NULL ENABLE, 
	"ID_EQUIPOLOCAL" NUMBER(*,0) NOT NULL ENABLE, 
	"ID_EQUIPOVISITANTE" NUMBER(*,0) NOT NULL ENABLE, 
	"ID_ESTADIO" NUMBER(*,0) NOT NULL ENABLE, 
	"ID_LESION" NUMBER(*,0) NOT NULL ENABLE, 
	"ID_COMPETICION" NUMBER(*,0) NOT NULL ENABLE, 
	"ID_ARBITRO" NUMBER(*,0) NOT NULL ENABLE, 
	"GOLESLOCAL" NUMBER(*,0) NOT NULL ENABLE, 
	"GOLESVISITANTE" NUMBER(*,0) NOT NULL ENABLE, 
	"POSESIONLOCAL" VARCHAR2(100) NOT NULL ENABLE, 
	"POSESIONVISITANTE" VARCHAR2(100) NOT NULL ENABLE, 
	"TIROSLOCAL" NUMBER(*,0) NOT NULL ENABLE, 
	"TIROSVISITANTE" NUMBER(*,0) NOT NULL ENABLE, 
	"TARJETASAMARILLASLOCAL" NUMBER(*,0) NOT NULL ENABLE, 
	"TARJETASAMARILLASVISITANTE" NUMBER(*,0) NOT NULL ENABLE, 
	"TARJETASROJASLOCAL" NUMBER(*,0) NOT NULL ENABLE, 
	"TARJETASROJASVISITANTE" NUMBER(*,0) NOT NULL ENABLE, 
	 CONSTRAINT "FACT_PARTIDO_PK" PRIMARY KEY ("ID_FECHA", "ID_EQUIPOLOCAL", "ID_EQUIPOVISITANTE", "ID_ESTADIO", "ID_LESION", "ID_COMPETICION", "ID_ARBITRO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

ALTER TABLE "lucas.lara"."FACT_PARTIDO" ADD CONSTRAINT "FK_DIM_ARBITRO" FOREIGN KEY ("ID_ARBITRO")
	  REFERENCES "lucas.lara"."DIM_ARBITRO" ("ID_ARBITRO") ENABLE;
  ALTER TABLE "lucas.lara"."FACT_PARTIDO" ADD CONSTRAINT "FK_DIM_COMPETICION" FOREIGN KEY ("ID_COMPETICION")
	  REFERENCES "lucas.lara"."DIM_COMPETICION" ("ID_COMPETICION") ENABLE;
  ALTER TABLE "lucas.lara"."FACT_PARTIDO" ADD CONSTRAINT "FK_DIM_EQUIPO_LOCAL" FOREIGN KEY ("ID_EQUIPOLOCAL")
	  REFERENCES "lucas.lara"."DIM_EQUIPO" ("ID_EQUIPO") ENABLE;
  ALTER TABLE "lucas.lara"."FACT_PARTIDO" ADD CONSTRAINT "FK_DIM_EQUIPO_VISITANTE" FOREIGN KEY ("ID_EQUIPOVISITANTE")
	  REFERENCES "lucas.lara"."DIM_EQUIPO" ("ID_EQUIPO") ENABLE;
  ALTER TABLE "lucas.lara"."FACT_PARTIDO" ADD CONSTRAINT "FK_DIM_ESTADIO" FOREIGN KEY ("ID_ESTADIO")
	  REFERENCES "lucas.lara"."DIM_ESTADIO" ("ID_ESTADIO") ENABLE;
  ALTER TABLE "lucas.lara"."FACT_PARTIDO" ADD CONSTRAINT "FK_DIM_FECHA" FOREIGN KEY ("ID_FECHA")
	  REFERENCES "lucas.lara"."DIM_FECHA" ("ID_FECHA") ENABLE;
  ALTER TABLE "lucas.lara"."FACT_PARTIDO" ADD CONSTRAINT "FK_DIM_LESION" FOREIGN KEY ("ID_LESION")
	  REFERENCES "lucas.lara"."DIM_LESION" ("ID_LESION") ENABLE;

CREATE UNIQUE INDEX "lucas.lara"."FACT_PARTIDO_PK" ON "lucas.lara"."FACT_PARTIDO" ("ID_FECHA", "ID_EQUIPOLOCAL", "ID_EQUIPOVISITANTE", "ID_ESTADIO", "ID_LESION", "ID_COMPETICION", "ID_ARBITRO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
;
